name: Packer Template Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Packer init
        run: |
          packer init .

      - name: Run Packer fmt
        id: packer-fmt
        run: |
          packer fmt -check=true .

      - name: Run Packer validate
        id: packer-validate
        run: |
          packer validate \
          -var "jenkins_admin_user=${{ secrets.JENKINS_ADMIN_USER }}" \
          -var "jenkins_admin_password=${{ secrets.JENKINS_ADMIN_PASSWORD }}" \
          -var "dockerhub_username=${{ secrets.DOCKERHUB_USERNAME }}" \
          -var "dockerhub_token=${{ secrets.DOCKERHUB_TOKEN }}" \
          -var "github_username=${{ secrets.GIT_USERNAME }}" \
          -var "github_token=${{ secrets.GIT_TOKEN }}" \
          .
